# Generated by Django 5.1.6 on 2025-07-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#2196F3', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.EmailField(default='medali@example.com', max_length=254),
        ),
    ]
