# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - mailhog
#     environment:
#       - EMAIL_HOST=mailhog
#       - EMAIL_PORT=1025
#       - EMAIL_USE_TLS=False
#       - EMAIL_USE_SSL=False
#       - DEFAULT_FROM_EMAIL=admin@example.com

#   mailhog:
#     image: mailhog/mailhog
#     restart: always
#     ports:
#       - "1025:1025"  # SMTP server
#       - "8025:8025"  # Web UI
