# Generated by Django 5.1.6 on 2025-06-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='method',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='status',
        ),
        migrations.AddField(
            model_name='reminder',
            name='email_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='in_app_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=50, null=True),
        ),
    ]
