# Generated by Django 5.1.6 on 2025-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, help_text="Details about user's experience", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills', max_length=255, null=True),
        ),
    ]
