# Generated by Django 5.1.6 on 2025-07-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0002_project_last_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['project', '-timestamp'], name='activity_ac_project_23db08_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='activity_ac_user_id_d16f44_idx'),
        ),
    ]
